window.PO_DATA = {
  africa: {
    id: "africa",
    name: "AFRICAN SAVANNA",
    blurb: "Golden grasslands under a hard sun.",
    ground: ["#c4a35a", "#b8944a", "#d2b36a", "#a8823c"],
    path: "#8a6b35",
    water: "#2a6a7a",
    sky: ["#f0c878", "#e8a050", "#c87838"],
    accent: "#2d5a28",
    animals: [
      {id:"lion",name:"Lion",latin:"Panthera leo",danger:"Apex · Ambush + pride hunt",x:18,y:14,color:"#c9a227",
        facts:["Only truly social big cats—prides share territory and cub care."],
        myths:["Many African traditions cast lions as kingship and ancestral guardians."],
        fun:["Darker manes often signal stronger males."],
        survive:["Never approach a pride, especially with cubs—back away slowly."]},
      {id:"hippo",name:"Hippopotamus",latin:"Hippopotamus amphibius",danger:"Extremely territorial in water",x:42,y:22,color:"#6b5b5b",
        facts:["Among Africa’s deadliest large mammals—mostly shoreline encounters."],
        myths:["Egypt linked hippos to chaos and protective magic."],
        fun:["‘Yawns’ are threat displays, not sleepiness."],
        survive:["Never get between a hippo and deep water."]},
      {id:"buffalo",name:"Cape Buffalo",latin:"Syncerus caffer",danger:"Unpredictable · Charges when pressed",x:28,y:30,color:"#3a3030",
        facts:["Nicknamed ‘Black Death’ for tenacity when cornered."],
        myths:["Safari lore says wounded buffalo stalk hunters."],
        fun:["Oxpeckers ride along picking ticks."],
        survive:["Don’t cut off a herd’s escape route."]},
      {id:"rhino",name:"Rhinoceros",latin:"Diceros / Ceratotherium",danger:"Charge · Poor eyesight · Huge mass",x:55,y:18,color:"#8a8580",
        facts:["Living armor from deep time—black and white African rhinos."],
        myths:["Unicorn myths clung to rhinos for centuries."],
        fun:["Surprising charge speed for their bulk."],
        survive:["Don’t corner or surprise one on foot."]},
      {id:"croc",name:"Nile Crocodile",latin:"Crocodylus niloticus",danger:"Ambush · Water edge killer",x:12,y:26,color:"#3f5a32",
        facts:["Patient ambush hunters at Africa’s water edges."],
        myths:["Egypt linked crocodiles to Sobek—Nile power and threat."],
        fun:["They can go long stretches between big meals."],
        survive:["Never swim opaque water or stand alone on muddy banks."]}
    ]
  },
  mountains: {
    id: "mountains",
    name: "HIGH PEAKS",
    blurb: "Thin air, hard stone, sharp hunters.",
    ground: ["#6e6a66", "#5a5652", "#7a7670", "#8a8680"],
    path: "#4a4642",
    water: "#4a6a7a",
    sky: ["#7ec8e8", "#b8d4e8", "#e8f0f6"],
    accent: "#2f4a2f",
    snow: true,
    animals: [
      {id:"grizzly",name:"Grizzly Bear",latin:"Ursus arctos horribilis",danger:"Powerful · Food-conditioned risk",x:20,y:20,color:"#6b4423",
        facts:["Shoulder hump is muscle for digging and swipes."],
        myths:["Indigenous stories treat bears as kin or spirit teachers."],
        fun:["The hump isn’t fat—it’s muscle."],
        survive:["Make noise; store food in bear-proof containers."]},
      {id:"wolf",name:"Gray Wolf",latin:"Canis lupus",danger:"Pack hunter · Rarely targets humans",x:40,y:16,color:"#7a7a7a",
        facts:["Hunts with stamina and strategy more than size."],
        myths:["Werewolf legends twisted wolf fear into cursed humans."],
        fun:["Howls travel kilometers to reunite packmates."],
        survive:["Secure food and pets; never feed wildlife."]},
      {id:"cougar",name:"Mountain Lion",latin:"Puma concolor",danger:"Silent stalker · Ambush specialist",x:52,y:28,color:"#b8894a",
        facts:["Also cougar, puma, or panther—one wide-ranging species."],
        myths:["Black ‘panthers’ are often other cats—or mis-seen cougars."],
        fun:["They can’t roar—they scream, purr, and chirp."],
        survive:["Hike in groups; keep kids close."]},
      {id:"eagle",name:"Golden Eagle",latin:"Aquila chrysaetos",danger:"Aerial predator · Huge talons",x:30,y:10,color:"#8a5a20",
        facts:["Soars on mountain thermals with razor vision."],
        myths:["Eagles signal sky power and divine messengers across cultures."],
        fun:["Spot prey from astonishing heights."],
        survive:["Give nest cliffs space in breeding season."]},
      {id:"snowleopard",name:"Snow Leopard",latin:"Panthera uncia",danger:"Ghost of cliffs · Livestock conflict",x:14,y:32,color:"#c5d0dc",
        facts:["High Asia specialist—often 3,000–5,500 m."],
        myths:["Mountain omen and spirit of high country."],
        fun:["Long tails are balance poles and winter scarves."],
        survive:["Rarely threatens people—livestock conflict drives killing."]}
    ]
  },
  jungle: {
    id: "jungle",
    name: "DEEP JUNGLE",
    blurb: "Green walls, wet air, hidden eyes.",
    ground: ["#2f5a28", "#3a6a30", "#245020", "#356235"],
    path: "#1e3a1a",
    water: "#1a4a4a",
    sky: ["#1a3028", "#243828", "#305038"],
    accent: "#6a2a6a",
    mist: true,
    animals: [
      {id:"jaguar",name:"Jaguar",latin:"Panthera onca",danger:"Ambush · Bone-crushing bite",x:22,y:18,color:"#c47a20",
        facts:["Strongest bite among big cats relative to size."],
        myths:["Mesoamerica linked jaguars to kings, night, and underworld."],
        fun:["‘Black panthers’ here are usually melanistic jaguars."],
        survive:["Avoid dawn/dusk alone near water."]},
      {id:"anaconda",name:"Green Anaconda",latin:"Eunectes murinus",danger:"Constriction · Aquatic ambush",x:48,y:24,color:"#3a6a28",
        facts:["Among the heaviest snakes—wait in water for large prey."],
        myths:["Explorer yarns of 30 m monsters outran evidence."],
        fun:["Females larger than males."],
        survive:["Treat muddy banks and oxbows as ambush zones."]},
      {id:"gorilla",name:"Gorilla",latin:"Gorilla beringei / gorilla",danger:"Silverback defense · Disease risk",x:14,y:28,color:"#2f2f36",
        facts:["Largest living primates—need vast intact forest."],
        myths:["Cast as ancestral forest kin in Central Africa."],
        fun:["A silverback’s chest-beat is language and thunder."],
        survive:["Silverbacks defend groups—keep respectful distance."]},
      {id:"tiger",name:"Tiger",latin:"Panthera tigris",danger:"Ambush sovereign · Night hunter",x:36,y:32,color:"#e07a2a",
        facts:["Largest living cat—solitary striped ambush hunter."],
        myths:["From Chinese guardians to Durga’s mount."],
        fun:["Night roar shakes the jungle’s nerves."],
        survive:["Never trek reserves without guides."]},
      {id:"leopard",name:"Leopard",latin:"Panthera pardus",danger:"Ambush master · Night phantom",x:56,y:14,color:"#c49a4a",
        facts:["Adaptable from rainforest to semi-desert."],
        myths:["Crest animal—stealth and lethal patience."],
        fun:["A tail twitch tips perfect camouflage."],
        survive:["Keep dogs and livestock secured at night."]}
    ]
  }
};
